version: "3.8"
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${DB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${DB_ROOT_PASSWORD}"