version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "admin"
      MONGO_DATABASE: "${DB_NAME}"
      MONGO_USERNAME: "${DB_USERNAME}"
      MONGO_PASSWORD: "${DB_PASSWORD}"
